"""Add status to absensi

Revision ID: 128429b2d013
Revises: 55ad4a8c76d2
Create Date: 2020-01-23 22:36:30.145550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128429b2d013'
down_revision = '55ad4a8c76d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('status_hadir_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendance', 'status_hadir', ['status_hadir_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'status_hadir_id')
    # ### end Alembic commands ###
