"""add hari in jadwal

Revision ID: 1c3df4e3b780
Revises: 05c2a77954de
Create Date: 2020-01-22 21:12:27.203751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3df4e3b780'
down_revision = '05c2a77954de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jadwal', sa.Column('hari_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jadwal', 'hari', ['hari_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jadwal', type_='foreignkey')
    op.drop_column('jadwal', 'hari_id')
    # ### end Alembic commands ###
