"""Add Absensi Table

Revision ID: 55ad4a8c76d2
Revises: fefbc8c6a833
Create Date: 2020-01-23 22:32:27.971065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ad4a8c76d2'
down_revision = 'fefbc8c6a833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_time', sa.Time(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('pelaksanaan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pelaksanaan_id'], ['pelaksanaan.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
