"""Add iso_week_day to hari

Revision ID: 58b6c8bdf466
Revises: 128429b2d013
Create Date: 2020-01-23 22:51:15.549240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b6c8bdf466'
down_revision = '128429b2d013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hari', sa.Column('iso_week_day', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'hari', ['iso_week_day'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hari', type_='unique')
    op.drop_column('hari', 'iso_week_day')
    # ### end Alembic commands ###
