"""Add absensi_jadwal and StatusHadir

Revision ID: 5cdc17d45477
Revises: 811dd4b70593
Create Date: 2020-01-22 22:17:20.021805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cdc17d45477'
down_revision = '811dd4b70593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_hadir',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('absensi_jadwal',
    sa.Column('jadwal_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status_hadir_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['jadwal_id'], ['jadwal.id'], ),
    sa.ForeignKeyConstraint(['status_hadir_id'], ['status_hadir.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('jadwal_id', 'student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('absensi_jadwal')
    op.drop_table('status_hadir')
    # ### end Alembic commands ###
