"""Add Pelaksanaan Table

Revision ID: fefbc8c6a833
Revises: 5cdc17d45477
Create Date: 2020-01-23 22:20:53.626341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefbc8c6a833'
down_revision = '5cdc17d45477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pelaksanaan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('jadwal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jadwal_id'], ['jadwal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pelaksanaan')
    # ### end Alembic commands ###
